import React from 'react';

const ScorecardForm: React.FC = () => (
  <div className={'grid border-2 border-green-500 w-full`}; grid-template-columns: 3fr repeat(9, 1fr) 1.5fr 1fr 1fr 2fr;'}>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">Hole</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">1</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">2</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">4</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">5</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">6</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">7</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">8</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">9</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">Total</div>
    <div className="col-start-12 col-span-3" />
    <div className="border-2 border-orange-500 border-solid justify-center text-center">Men</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">316</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">294</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">309</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">144</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">490</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">245</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">361</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">184</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">473</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">2816</div>
    <div className="col-start-12 col-span-3" />
    <div className="border-2 border-orange-500 border-solid justify-center text-center">Par</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">4</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">4</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">4</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">5</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">4</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">4</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">5</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">36</div>
    <div className="col-start-12 col-span-3" />
    <div className="border-2 border-orange-500 border-solid justify-center text-center">Handicap</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">7</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">11</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">5</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">15</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">13</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">17</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">1</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">9</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>

    <div className="col-start-12 col-span-3" />
    <div className="col-span-10">#1 Team 1</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">Total</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">Hcp</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">Net</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">Points</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">Name</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">27</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">27</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">Points</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">27</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">27</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">Gold</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">249</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">238</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">224</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">140</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">456</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">241</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">282</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">181</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">392</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">2403</div>
    <div className="col-start-12 col-span-3" />
    <div className="border-2 border-orange-500 border-solid justify-center text-center">Handicap</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">11</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">7</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">13</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">17</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">15</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">5</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">9</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">1</div>
    <div className="col-start-12 col-span-3" />
    <div className="col-span-10">#1 Team 1</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">Total</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">Hcp</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">Net</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">Points</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">Name</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">27</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">27</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">Points</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">27</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">27</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">Gold</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">249</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">238</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">224</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">140</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">456</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">241</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">282</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">181</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">392</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">2403</div>
    <div className="col-start-12 col-span-3" />
    <div className="border-2 border-orange-500 border-solid justify-center text-center">Handicap</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">11</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">7</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">13</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">17</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">3</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">15</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">5</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">9</div>
    <div className="border-2 border-orange-500 border-solid justify-center text-center">1</div>

    <div className="col-start-12 col-span-3" />

  </div>
);


export default ScorecardForm;
