export const data = {
  name: 'Manor Valley Golf Club',
  tees: [
    {
      name: 'Blue',
      rating: 68.1,
      par: 72,
      length: 5922,
      f9length: 2888,
      b9length: 3034,
      id: 1,
      courseId: 1,
      holes: [
        {
          number: 1,
          handicap: 7,
          par: 4,
          length: 324,
        },
        {
          number: 2,
          handicap: 11,
          par: 4,
          length: 303,
        },

        {
          number: 3,
          handicap: 5,
          par: 4,
          length: 315,
        },
        {
          number: 4,
          handicap: 15,
          par: 3,
          length: 151,
        },
        {
          number: 5,
          handicap: 13,
          par: 5,
          length: 515,
        },
        {
          number: 6,
          handicap: 17,
          par: 4,
          length: 246,
        },
        {
          number: 7,
          handicap: 1,
          par: 4,
          length: 365,
        },
        {
          number: 8,
          handicap: 9,
          par: 3,
          length: 188,
        },
        {
          number: 9,
          handicap: 3,
          par: 5,
          length: 481,
        },
        {
          number: 10,
          handicap: 4,
          par: 4,
          length: 374,
        },
        {
          number: 11,
          handicap: 18,
          par: 4,
          length: 299,
        },
        {
          number: 12,
          handicap: 8,
          par: 3,
          length: 186,
        },
        {
          number: 13,
          handicap: 6,
          par: 5,
          length: 488,
        },
        {
          number: 14,
          handicap: 16,
          par: 4,
          length: 299,
        },
        {
          number: 15,
          handicap: 2,
          par: 4,
          length: 390,
        },
        {
          number: 16,
          handicap: 10,
          par: 4,
          length: 380,
        },
        {
          number: 17,
          handicap: 14,
          par: 4,
          length: 310,
        },
        {
          number: 18,
          handicap: 12,
          par: 4,
          length: 308,
        },
      ],
    },
    {
      name: 'White',
      rating: 66.8,
      par: 72,
      length: 5715,
      f9length: 2794,
      b9length: 2921,
      id: 5,
      courseId: 1,
      holes: [
        {
          number: 1,
          handicap: 7,
          par: 4,
          length: 315,
        },
        {
          number: 2,
          handicap: 11,
          par: 4,
          length: 297,
        },
        {
          number: 3,
          handicap: 5,
          par: 4,
          length: 306,
        },
        {
          number: 4,
          handicap: 15,
          par: 3,
          length: 144,
        },
        {
          number: 5,
          handicap: 13,
          par: 5,
          length: 491,
        },
        {
          number: 6,
          handicap: 17,
          par: 4,
          length: 239,
        },
        {
          number: 7,
          handicap: 1,
          par: 4,
          length: 355,
        },
        {
          number: 8,
          handicap: 9,
          par: 3,
          length: 183,
        },
        {
          number: 9,
          handicap: 3,
          par: 5,
          length: 464,
        },
        {
          number: 10,
          handicap: 4,
          par: 4,
          length: 364,
        },
        {
          number: 11,
          handicap: 18,
          par: 4,
          length: 292,
        },
        {
          number: 12,
          handicap: 8,
          par: 3,
          length: 176,
        },
        {
          number: 13,
          handicap: 6,
          par: 5,
          length: 451,
        },
        {
          number: 14,
          handicap: 16,
          par: 4,
          length: 294,
        },
        {
          number: 15,
          handicap: 2,
          par: 4,
          length: 378,
        },
        {
          number: 16,
          handicap: 10,
          par: 4,
          length: 374,
        },
        {
          number: 17,
          handicap: 14,
          par: 4,
          length: 306,
        },
        {
          number: 18,
          handicap: 12,
          par: 4,
          length: 286,
        }],
    },
    {
      name: 'Gold',
      rating: 65,
      par: 72,
      length: 5220,
      f9length: 2625,
      b9length: 2595,
      id: 6,
      courseId: 1,
      holes: [
        {
          number: 1,
          handicap: 7,
          par: 4,
          length: 304,
        },
        {
          number: 2,
          handicap: 11,
          par: 4,
          length: 282,
        },
        {
          number: 3,
          handicap: 5,
          par: 4,
          length: 295,
        },
        {
          number: 4,
          handicap: 15,
          par: 3,
          length: 137,
        },
        {
          number: 5,
          handicap: 13,
          par: 5,
          length: 456,
        },
        {
          number: 6,
          handicap: 17,
          par: 4,
          length: 236,
        },
        {
          number: 7,
          handicap: 1,
          par: 4,
          length: 349,
        },
        {
          number: 8,
          handicap: 9,
          par: 3,
          length: 175,
        },
        {
          number: 9,
          handicap: 3,
          par: 5,
          length: 391,
        },
        {
          number: 10,
          handicap: 4,
          par: 4,
          length: 347,
        },
        {
          number: 11,
          handicap: 18,
          par: 4,
          length: 282,
        },
        {
          number: 12,
          handicap: 8,
          par: 3,
          length: 96,
        },
        {
          number: 13,
          handicap: 6,
          par: 5,
          length: 375,
        },
        {
          number: 14,
          handicap: 16,
          par: 4,
          length: 287,
        },
        {
          number: 15,
          handicap: 2,
          par: 4,
          length: 267,
        },
        {
          number: 16,
          handicap: 10,
          par: 4,
          length: 365,
        },
        {
          number: 17,
          handicap: 14,
          par: 4,
          length: 299,
        },
        {
          number: 18,
          handicap: 12,
          par: 4,
          length: 277,
        },
      ],
    },
    {
      name: 'Red',
      rating: 69.5,
      par: 72,
      length: 5217,
      f9length: 2622,
      b9length: 2595,
      id: 7,
      courseId: 1,
      holes: [
        {
          number: 1,
          handicap: 11,
          par: 4,
          length: 304,
        },
        {
          number: 2,
          handicap: 9,
          par: 4,
          length: 282,
        },
        {
          number: 3,
          handicap: 5,
          par: 4,
          length: 295,
        },
        {
          number: 4,
          handicap: 17,
          par: 3,
          length: 137,
        },
        {
          number: 5,
          handicap: 7,
          par: 5,
          length: 456,
        },
        {
          number: 6,
          handicap: 13,
          par: 4,
          length: 236,
        },
        {
          number: 7,
          handicap: 1,
          par: 4,
          length: 349,
        },
        {
          number: 8,
          handicap: 15,
          par: 3,
          length: 175,
        },
        {
          number: 9,
          handicap: 3,
          par: 5,
          length: 388,
        },
        {
          number: 10,
          handicap: 4,
          par: 4,
          length: 347,
        },
        {
          number: 11,
          handicap: 16,
          par: 4,
          length: 282,
        },
        {
          number: 12,
          handicap: 18,
          par: 3,
          length: 96,
        },
        {
          number: 13,
          handicap: 2,
          par: 5,
          length: 375,
        }, {

          number: 14,
          handicap: 14,
          par: 4,
          length: 287,
        },
        {
          number: 15,
          handicap: 12,
          par: 4,
          length: 267,
        },
        {
          number: 16,
          handicap: 6,
          par: 4,
          length: 365,
        },
        {
          number: 17,
          handicap: 8,
          par: 4,
          length: 299,
        },
        {
          number: 18,
          handicap: 10,
          par: 4,
          length: 277,
        },
      ],
    },
  ],
  id: '1',
};
